#!/usr/bin/env php

<?php

/**
 * Created by PhpStorm.
 * User: linyang
 * Date: 2018/4/17
 * Time: 上午10:43
 *
 * Class Monitor
 * 监控类
 * 这里我们使用PHP自我实现了。。。:)
 */
class Monitor
{
    private $dingding = '';
    private $appName = '';
    private $slowlog = '';
    private $slowlogTimeout = 2;
    private $rate = 30;

    public function __construct()
    {
        if (!$appName = getenv('APP_NAME')) {
            exit;
        }
        if (!$dingding = getenv('APP_MONITOR_HOOK')) {
            exit;
        }
        if (!$slowlog = getenv('FPM_SLOWLOG')) {
            exit;
        }
        if ($slowlogTimeout = (int)getenv('FPM_SLOWLOG_TIMEOUT')) {
            $this->slowlogTimeout = $slowlogTimeout;
        }
        if ($rate = (int)getenv('APP_MONITOR_RATE')) {
            $this->rate = $rate;
        }
        $this->dingding = $dingding;
        $this->appName = $appName;
        $this->slowlog = $slowlog;
        $this->init();
    }

    private function init()
    {
        while (true) {
            if ($log = system("cat {$this->slowlog}")) {
                $this->sendPost($log);
                system("true > {$this->slowlog}");
            }

            $fpmNum = (int)system('ps axu | grep php-fpm | wc -l');
            if ($fpmNum >= 90) {
                $this->sendPost("php-fpm children will be not enough: {$fpmNum}");
            }
            sleep($this->rate);
        }
    }

    /**
     * 获取本地外网IP
     * @return mixed
     */
    private function serverIp()
    {
        return $_SERVER['SERVER_ADDR'];
    }

    /**
     * 发送请求
     * @param $content string
     * @return mixed
     */
    private function sendPost($content)
    {
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
        curl_setopt($ch, CURLOPT_URL, $this->dingding);
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_HEADER, false);
        curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/json;charset=utf-8;']);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_TIMEOUT, 2);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode([
            'msgtype' => 'text',
            'text' => ['content' => "php慢日志({$this->slowlogTimeout}s)上报:\napp: {$this->appName}\nip: {$this->serverIp()}\content:{$content}"],
            'at' => ['isAtAll' => true]
        ]));
        return curl_exec($ch);
    }
}

new Monitor();